# OAuth2 配置
security:
  oauth2:
    client:
      client-id: ENC(Hy6Gv+DzZ5qERdLYGhw57lLpKTPuvVIK)
      client-secret: ENC(VHWe9pujysH2cwAgSLruVgO5hwHP+l16)
      scope: server

# 数据源
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/ks_platform?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowMultiQueries=true
    username: root
    password: 123456

# 直接放行URL
ignore:
  urls:
    - /actuator/**
    - /examPlan/list
    - /examNode/info/*
