# OAuth2 配置
security:
  oauth2:
    client:
      client-id: ENC(2fn0EBfKK68uqaJ7xGIODg==)
      client-secret: ENC(tBueozMNazoLfagg0j0DXQ==)
      scope: server

# 数据源
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:10.0.0.100}:${MYSQL_PORT:3306}/sinotn_enms?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowMultiQueries=true
    username: root
    password: 123456

# 直接放行URL
ignore:
  urls:
    - /actuator/**

# 日志级别
logging:
  level:
    com.sinotn.exam.node: DEBUG
