# OAuth2 配置
security:
  oauth2:
    client:
      client-id: ENC(eT2rgSnKPtodUtU6uDmrqQ==)
      client-secret: ENC(Jn063Lk7vTXoGk9JZYBvFw==)
#      grant-type: client_credentials
      scope: server

# 数据源
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:10.0.0.100}:${MYSQL_PORT:3306}/exam_upms?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowMultiQueries=true
    username: root
    password: 123456

# 直接放行URL
ignore:
  urls:
    - /actuator/**
    - /user/info/*
    - /log/**
    - /user/addBatchUsers
