## spring messages 配置
security:
  oauth2:
    client:
      client-id: ENC(MfgVjcf7W3I5foH3WK2f6Q==)
      client-secret: ENC(HmYO8dpeg8RjtIiMGdD43w==)
      scope: server

# 数据源
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/ks_data?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowMultiQueries=true
    username: root
    password: 123456

# 直接放行URL
ignore:
  urls:
    - /actuator/**
