# OAuth2 配置
security:
  oauth2:
    client:
      client-id: ENC(eQJKcIdpz+o6eFNpjfmolg==)
      client-secret: ENC(WfZnGP6Gcd7e/l86lgO6fw==)
      scope: server

# 数据源
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/exam_train?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowMultiQueries=true
    username: root
    password: 123456

# 直接放行URL
ignore:
  urls:
    - /actuator/**
    - /administrative/**
